name: ExchangeMarket
main: com.samoatesgames.exchangemarket.ExchangeMarket
version: 1.0
authors: [SamOatesPlugins]
description: An item market exchange plugin for Minecraft.

commands:
    exchange:
        description: Access to all the market commands
        usage: /<command>
        aliases: [exchangemarket]